version: '3.9'

services:
  db:
    image: postgres:15
    container_name: nutriplan_postgres
    restart: always
    environment:
      POSTGRES_USER: nutriplan
      POSTGRES_PASSWORD: nutriplan123
      POSTGRES_DB: nutriplan_db
    ports:
      - "5432:5432"
    volumes:
      - nutriplan_data:/var/lib/postgresql/data

volumes:
  nutriplan_data:
